name: Generate SVG Reports

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib

      - name: Generate Contribution Calendar Heatmap
        run: python generate_heatmap.py

      - name: Generate Activity Pie Chart
        run: python generate_pie_chart.py

      - name: Generate Dynamic Bar Chart
        run: python generate_bar_chart.py

      - name: Generate GitHub Profile SVG Badge
        run: python generate_profile_badge.py

      - name: Generate Commit History Graph
        run: python generate_commit_history.py

      - name: Generate Repository Stars and Forks
        run: python generate_stars_forks.py

      - name: Generate Top Languages Used
        run: python generate_top_languages.py

      - name: Generate Latest Pull Requests
        run: python generate_latest_prs.py

      - name: Generate Recent Issues Opened
        run: python generate_recent_issues.py

      - name: Generate GitHub Contributions Timeline
        run: python generate_contributions_timeline.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.svg
          git commit -m "Update SVG reports"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
