name: Update Language Stats

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch: # Memungkinkan eksekusi manual

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python generate_language_stats.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add language_stats.md
          git commit -m "Update language stats"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
